name: Run Selenium Tests with Maven

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Change from windows-latest to ubuntu-latest

    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        ports:
          - 1523:1521
        env:
          ORACLE_PWD: Oracle123  # Change this if necessary
        options: >-
          --health-cmd="curl --silent --fail http://localhost:8080"  # Health check command
          --health-interval=30s
          --health-timeout=30s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # or 'zulu'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Selenium Tests
      run: mvn test
