name: Run Selenium Tests with Maven

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # or 'zulu'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install
