name: Run Selenium Tests with Maven

on:
  schedule:
    - cron: '30 23 * * *'   # Runs at 11:30 PM UTC → 5:00 AM IST
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner instead of ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make chromedriver executable
      run: |
        icacls "src/main/java/Repository/chromedriver-win64/chromedriver.exe" /grant Everyone:F

    - name: Install Chrome
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile "chrome_installer.exe"
        Start-Process -FilePath "chrome_installer.exe" -ArgumentList "/silent /install" -Wait

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven and run
      run: mvn clean install
